<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>preview</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
    <ItemGroup>
      <ProjectReference Include="..\Alloy.Common\Alloy.Common.csproj" />
      <ProjectReference Include="..\Alloy.ContentReader\Alloy.ContentReader.csproj" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.8" />
      <PackageReference Include="OpenTK" Version="5.0.0-pre.16" />
    </ItemGroup>
</Project>