<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>preview</LangVersion>
    </PropertyGroup>
	<ItemGroup>
        <PackageReference Include="OpenTK" Version="5.0.0-pre.15" />
        <PackageReference Include="ReFuel.StbImage" Version="2.1.0" />
    </ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\AlloyClient.Engine\AlloyClient.Engine.csproj" />
	</ItemGroup>
</Project>
