<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
	<ItemGroup>
        <PackageReference Include="OpenTK" Version="5.0.0-pre.14" />
        <PackageReference Include="ReFuel.StbImage" Version="2.1.0" />
    </ItemGroup>
</Project>
